### ISSUE TITLE
您好，请教一个打包的问题。

### ISSUE THREAD

**Issue by cnsnake11** [xueduany/react-mix#1]
支持ReactNative代码的分割打包

您好，问一下这块大概的实现思路是怎么做到的呢？主要想知道是如何分割打包的。。

期待您的回复，万分感谢。

**Comment by xueduany** [comment]
这块的难点，主要在于各个打包框架，对于ES6的define,require,import做了各自的实现，虽然大同小异，但是方法名不一样，之前我尝试过修改成为基于webpack的方式做打包，但是因为方法名问题，导致合并了不能用，这次直接反其道而行之，就基于reactpackager自己打包，因为不管怎么做，打包的先后顺序还是按照我们在代码里面实现的先后顺序来实现的，我们只要把通用的方法，都挂在第一个common包里面，挂在globalScope上，第二个包就不需要再require这些，直接可以使用GlobalScope的全局对象，也就实现了common和bus包的拆分，具体的代码实现请看react-native.js.split.build.js

**Comment by cnsnake11** [comment]
万分感谢。
